# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Arren Glover
logo: /assets/img/arrenandicub.jpg
email: arrenDOTgloverATgmailDOTcom
github_logo: /assets/img/github.png
scholar_url: https://scholar.google.com/citations?user=GGeia84AAAAJ&hl=en
scholar_logo: /assets/img/scholar.png
linkedin_url: https://www.linkedin.com/in/arren-glover
linkedin_logo: /assets/img/lin.png
cv_url: https://www.overleaf.com/read/yvtmxcqbbjsz
overleaf_logo: /assets/img/overleaf.png
description: >- # this means to ignore newlines until "baseurl:"
  I want to improve robots with low-latency vision using event-cameras. Real-time algorithms with closed-loop control for mobile and humanoid robots.<p>
  I have experience with 6-DoF object tracking, human pose estimation, 6-DoF SLAM, feature tracking, visual-inertial integration, appearance-based SLAM, robots with language models, and developmental algorithms.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
#github_username:  arrenglover

position: >-
  I currently hold a researcher position at the Italian Institute of Technology.
position_url: https://edpr.iit.it/
position_logo: /assets/img/IIT-EDR-logo-t1.png


# Build settings
#markdown: kramdown
#theme: minima
github:
  is_project_page: false
  is_user_page: true
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
#plugins:
#  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
